name: dev_widgets
version: 1.0.1+1
publish_to: none
description: Cross-platform utilities for developers.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  brazil: ^1.0.0
  characters: ^1.2.1
  code_text_field: ^1.1.0
  dropdown_search: ^5.0.3
  easy_localization: ^3.0.1
  easy_localization_loader: ^1.0.1+1
  file_picker: ^5.2.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_markdown: ^0.6.12
  flutter_riverpod: ^2.0.2
  flutter_widget_from_html: ^0.8.5
  go_router: ^9.0.0
  highlight: ^0.7.0
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.1.1
  html_unescape: ^2.0.0
  ipsum: ^1.0.1
  json2yaml: ^3.0.0
  json_to_dart: ^1.0.5
  multi_split_view: ^2.1.0
  package_info_plus: ^4.0.2
  path: ^1.8.2
  path_provider: ^2.0.11
  pretty_diff_text: ^1.0.0
  recase: ^4.1.0
  responsive_framework: ^0.2.0
  screenshot: ^2.1.0
  url_launcher: ^6.1.6
  uuid: ^3.0.6
  xml: ^6.1.0
  yaml: ^3.1.1
  yaru: ^0.3.3
  yaru_colors: ^0.1.0
  yaru_widgets: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0
  
flutter:
  assets:
    - assets/icon/icon.png
    - assets/translations/
    
  fonts:
    - family: Fira Code
      fonts:
        - asset: fonts/FiraCode-Regular.ttf

    - family: Hack
      fonts:
        - asset: fonts/Hack-Regular.ttf

    - family: Monocraft
      fonts:
        - asset: fonts/Monocraft.otf

    - family: JetBrains Mono
      fonts:
        - asset: fonts/JetBrainsMonoNL-Regular.ttf
  uses-material-design: true

flutter_icons:
  image_path: "assets/icon/icon.png"
  web:
    generate: true
  windows:
    generate: true
  linux:
    generate: true
